_target_: atom.backgroundFlow.flowModel.powerLaw
uRef: None # need to get this from the sonic in AuxData
zRef: 8 # m, height of sonic anemometer above ground level
shearExponent: 0.2 # Default value for conventionally neutral boundary layer